{% set name = "bm3d" %}
{% set version = "3.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bm3d-{{ version }}.tar.gz
  sha256: ca6e416f9ec491ca3c408ad796efd3115479177998d50b2c1a2f83fda75648ef

build:
  number: 0
  skip: True  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - openblas
  run:
    - numpy
    - python
    - pywavelets
    - scipy
    - libblas * *openblas
    - openblas
    - libopenblas

test:
  imports:
    - bm3d
  requires:
    - pip
    - pytest
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest tests/bm3d_input_consistency.py tests/psd_resizing_and_parameters.py

about:
  home: https://pypi.org/project/bm3d/
  summary: BM3D for correlated noise.
  license: Other
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
    - ymirm
