{% set name = "bm3d" %}
{% set version = "3.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bm3d-{{ version }}.tar.gz
  sha256: ca6e416f9ec491ca3c408ad796efd3115479177998d50b2c1a2f83fda75648ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - cython
    - numpy
    - pip
    - python >=3.5
  run:
    - numpy
    - python >=3.5
    - pywavelets
    - scipy
    - openblas-devel

test:
  imports:
    - bm3d
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/bm3d/
  summary: BM3D for correlated noise.
  license: BSD-4-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
